//
//  RainbowWaveIndicator.swift
//  Hygge — the six-dot "rainbow wave" loading indicator.
//
//  Reverse-engineered frame-by-frame from a reference screen recording (the
//  "ss loop" method: track every dot's centroid per frame, then replay). Six
//  dots — yellow · orange · red · purple · blue · green — sit in a centred row
//  and ripple UPWARD in a left-to-right travelling wave: each dot lifts ~2.7×
//  its own diameter, holds near the top, then falls back through rest with a
//  soft overshoot before settling. Period ≈ 1.987s.
//
//  The vertical motion is not an approximation — `dotCurves` is the MEASURED
//  per-dot trajectory (0 = rest, 1 = full lift), sampled at 120 phases across
//  one period, so the loop matches the source 1:1. A single shared "master"
//  curve + phase delay was tried and rejected: the trailing dots move on a
//  visibly gentler curve than the lead dot, so each dot keeps its own track.
//
//  Motion notes (emil-design-eng): only `offset`/`opacity` animate (GPU-cheap),
//  driven by `TimelineView(.animation)` so the loop is seamless and phase-exact
//  regardless of when it mounts. Reduce Motion swaps the vertical travel for a
//  calm left-to-right opacity shimmer — gentler, never zero.
//

import SwiftUI

struct RainbowWaveIndicator: View {
    /// Dot diameter in points. Spacing and lift scale from this, so the whole
    /// indicator stays in proportion at any size.
    var dotDiameter: CGFloat = 14

    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    // Geometry ratios measured from the 504px-wide source capture:
    //   centre spacing 19.4 / diameter 14.5 ≈ 1.34
    //   peak lift      40.2 / diameter 14.5 ≈ 2.77
    private var centerSpacing: CGFloat { dotDiameter * 1.34 }
    private var lift: CGFloat { dotDiameter * 2.77 }

    private static let period: Double = 1.987

    private static let colors: [Color] = [
        Color(hex: 0xFED218), // yellow
        Color(hex: 0xFD7C16), // orange
        Color(hex: 0xF2164B), // red
        Color(hex: 0x7B61E3), // purple
        Color(hex: 0x08A9E6), // blue
        Color(hex: 0x02B64C), // green
    ]

    var body: some View {
        if reduceMotion {
            TimelineView(.animation) { timeline in
                // Reduce Motion: no vertical travel and no left→right marquee — the
                // whole row breathes opacity in unison (a calm cross-fade, never zero).
                let s = 0.5 + 0.5 * cos(phase(timeline.date) * 2 * .pi)
                dotRow { _ in (offsetY: 0, opacity: 0.45 + 0.55 * s) }
            }
        } else {
            TimelineView(.animation) { timeline in
                let p = phase(timeline.date)
                dotRow { i in
                    (offsetY: -Self.sample(dot: i, at: p) * lift, opacity: 1)
                }
            }
        }
    }

    // MARK: - Row

    private func dotRow(_ state: @escaping (Int) -> (offsetY: CGFloat, opacity: Double)) -> some View {
        HStack(spacing: centerSpacing - dotDiameter) {
            ForEach(0..<6, id: \.self) { i in
                let s = state(i)
                Circle()
                    .fill(Self.colors[i])
                    .frame(width: dotDiameter, height: dotDiameter)
                    .opacity(s.opacity)
                    .offset(y: s.offsetY)
            }
        }
        // Reserve the full travel so a lifted dot is never clipped and the row
        // stays vertically centred on its rest line.
        .frame(height: dotDiameter + lift * 2)
    }

    // MARK: - Curve lookup

    private func phase(_ date: Date) -> Double {
        let t = date.timeIntervalSinceReferenceDate.truncatingRemainder(dividingBy: Self.period)
        return t / Self.period
    }

    /// Linearly interpolate dot `i`'s measured curve at normalized phase `p` (0…1).
    static func sample(dot i: Int, at p: Double) -> CGFloat {
        let arr = dotCurves[i]
        let n = arr.count
        var pp = p.truncatingRemainder(dividingBy: 1)
        if pp < 0 { pp += 1 }
        let f = pp * Double(n)
        let a = Int(f) % n
        let b = (a + 1) % n
        let frac = CGFloat(f - Double(Int(f)))
        return arr[a] * (1 - frac) + arr[b] * frac
    }
}

// MARK: - Measured per-dot vertical curves
//
// value × lift = upward offset (points). rest = 0, full lift ≈ 1, soft overshoot
// dips slightly negative. Period ≈ 1.987s, 120 samples/dot. Generated by tracking
// each dot's centroid across the reference recording — do not hand-edit.

private let dotCurves: [[CGFloat]] = [
  [0.048,0.049,0.050,0.048,0.044,0.039,0.034,0.031,0.024,0.018,0.013,0.009,
   0.004,-0.000,-0.003,-0.005,-0.006,-0.006,-0.006,-0.004,-0.004,-0.002,0.061,0.230,
   0.401,0.573,0.748,0.930,0.940,0.950,0.959,0.965,0.971,0.976,0.978,0.981,
   0.985,0.988,0.991,0.994,0.996,0.999,1.000,1.000,1.000,0.999,0.996,0.993,
   0.989,0.985,0.978,0.969,0.960,0.952,0.932,0.910,0.885,0.856,0.819,0.784,
   0.765,0.725,0.679,0.625,0.562,0.489,0.407,0.315,0.210,0.117,0.035,-0.029,
   -0.078,-0.105,-0.113,-0.129,-0.139,-0.143,-0.140,-0.132,-0.121,-0.102,-0.079,-0.049,
   -0.018,0.012,0.040,0.052,0.073,0.087,0.098,0.105,0.109,0.108,0.103,0.095,
   0.084,0.070,0.051,0.032,0.023,0.005,-0.010,-0.023,-0.033,-0.039,-0.043,-0.045,
   -0.046,-0.043,-0.039,-0.032,-0.022,-0.016,-0.005,0.005,0.015,0.025,0.033,0.039],
  [0.024,0.032,0.037,0.042,0.045,0.046,0.046,0.045,0.043,0.040,0.034,0.029,
   0.022,0.016,0.009,0.004,-0.000,-0.004,-0.007,-0.008,-0.009,-0.010,0.049,0.208,
   0.371,0.536,0.706,0.883,0.900,0.915,0.928,0.937,0.946,0.953,0.956,0.962,
   0.967,0.973,0.977,0.982,0.986,0.990,0.993,0.995,0.997,0.998,0.998,0.998,
   0.999,0.998,0.996,0.994,0.991,0.987,0.978,0.967,0.954,0.938,0.917,0.898,
   0.887,0.865,0.840,0.811,0.778,0.739,0.696,0.642,0.556,0.456,0.349,0.239,
   0.133,0.059,0.037,-0.009,-0.048,-0.079,-0.104,-0.123,-0.142,-0.148,-0.146,-0.133,
   -0.115,-0.090,-0.061,-0.048,-0.021,0.003,0.027,0.048,0.067,0.083,0.096,0.104,
   0.108,0.107,0.099,0.087,0.080,0.065,0.049,0.032,0.017,0.003,-0.010,-0.022,
   -0.032,-0.040,-0.045,-0.047,-0.045,-0.043,-0.038,-0.031,-0.022,-0.012,-0.003,0.006],
  [-0.011,-0.001,0.007,0.017,0.026,0.034,0.040,0.043,0.048,0.049,0.050,0.048,
   0.046,0.042,0.036,0.030,0.023,0.017,0.011,0.006,0.004,0.001,0.052,0.194,
   0.341,0.493,0.651,0.818,0.842,0.863,0.883,0.896,0.909,0.921,0.926,0.935,
   0.942,0.950,0.957,0.965,0.971,0.979,0.985,0.990,0.993,0.996,0.998,0.999,
   1.000,1.001,1.001,1.002,1.002,1.002,1.000,0.997,0.992,0.985,0.975,0.965,
   0.959,0.947,0.933,0.917,0.898,0.877,0.853,0.824,0.778,0.726,0.664,0.590,
   0.503,0.414,0.381,0.303,0.218,0.140,0.073,0.019,-0.041,-0.077,-0.105,-0.125,
   -0.137,-0.140,-0.135,-0.129,-0.114,-0.095,-0.073,-0.050,-0.025,-0.001,0.024,0.048,
   0.069,0.087,0.099,0.106,0.106,0.105,0.100,0.092,0.082,0.069,0.055,0.039,
   0.023,0.007,-0.007,-0.019,-0.030,-0.034,-0.040,-0.043,-0.043,-0.040,-0.036,-0.029],
  [-0.037,-0.032,-0.028,-0.020,-0.011,-0.001,0.008,0.014,0.023,0.031,0.039,0.045,
   0.049,0.052,0.053,0.051,0.049,0.045,0.039,0.033,0.030,0.025,0.063,0.176,
   0.296,0.425,0.564,0.713,0.750,0.785,0.815,0.836,0.856,0.874,0.881,0.893,
   0.904,0.915,0.924,0.935,0.945,0.958,0.968,0.976,0.982,0.988,0.993,0.995,
   0.998,1.001,1.004,1.006,1.008,1.009,1.010,1.011,1.010,1.009,1.007,1.003,
   1.001,0.995,0.988,0.979,0.968,0.956,0.941,0.925,0.899,0.871,0.838,0.799,
   0.754,0.707,0.689,0.642,0.578,0.504,0.421,0.332,0.230,0.143,0.068,0.003,
   -0.046,-0.084,-0.112,-0.120,-0.133,-0.136,-0.133,-0.125,-0.113,-0.096,-0.073,-0.048,
   -0.023,0.004,0.033,0.059,0.070,0.089,0.103,0.112,0.113,0.111,0.106,0.098,
   0.087,0.074,0.060,0.044,0.025,0.016,0.001,-0.014,-0.026,-0.035,-0.039,-0.042],
  [-0.041,-0.046,-0.049,-0.049,-0.047,-0.042,-0.035,-0.030,-0.022,-0.012,-0.002,0.009,
   0.019,0.028,0.035,0.040,0.044,0.045,0.045,0.044,0.043,0.041,0.062,0.125,
   0.202,0.293,0.400,0.520,0.587,0.645,0.695,0.729,0.758,0.784,0.794,0.813,
   0.829,0.846,0.862,0.879,0.894,0.912,0.925,0.937,0.946,0.953,0.960,0.963,
   0.969,0.973,0.977,0.982,0.985,0.987,0.991,0.994,0.995,0.997,0.998,0.999,
   0.998,0.997,0.995,0.993,0.989,0.984,0.978,0.971,0.957,0.942,0.923,0.901,
   0.876,0.851,0.841,0.816,0.783,0.744,0.700,0.647,0.578,0.501,0.411,0.302,
   0.197,0.101,0.019,-0.010,-0.058,-0.089,-0.113,-0.130,-0.142,-0.147,-0.146,-0.137,
   -0.124,-0.105,-0.076,-0.046,-0.031,-0.003,0.025,0.050,0.068,0.083,0.095,0.103,
   0.106,0.106,0.101,0.093,0.078,0.069,0.053,0.035,0.018,0.001,-0.012,-0.023],
  [0.003,-0.011,-0.022,-0.032,-0.039,-0.044,-0.046,-0.046,-0.046,-0.043,-0.036,-0.028,
   -0.019,-0.009,0.003,0.012,0.021,0.028,0.035,0.040,0.042,0.045,0.049,0.058,
   0.075,0.107,0.165,0.242,0.328,0.416,0.501,0.561,0.612,0.655,0.672,0.704,
   0.730,0.756,0.780,0.804,0.827,0.853,0.873,0.891,0.904,0.915,0.926,0.930,
   0.938,0.945,0.953,0.960,0.965,0.969,0.976,0.980,0.984,0.988,0.993,0.995,
   0.996,0.997,0.998,0.999,0.998,0.998,0.996,0.993,0.988,0.981,0.971,0.961,
   0.948,0.934,0.929,0.915,0.897,0.875,0.851,0.822,0.785,0.745,0.697,0.624,
   0.538,0.438,0.330,0.280,0.187,0.110,0.044,-0.008,-0.050,-0.082,-0.109,-0.130,
   -0.143,-0.149,-0.144,-0.131,-0.122,-0.103,-0.079,-0.053,-0.029,-0.003,0.021,0.044,
   0.065,0.082,0.094,0.102,0.104,0.102,0.097,0.089,0.077,0.064,0.049,0.034],
]

#if DEBUG
#Preview("Rainbow wave") {
    ZStack {
        LinearGradient(colors: [Color(hex: 0x23272E), Color(hex: 0x15171A)],
                       startPoint: .top, endPoint: .bottom).ignoresSafeArea()
        RainbowWaveIndicator(dotDiameter: 16)
    }
}
#endif
