//
//  TownRainRoster.swift
//  Block Party — which real St. Joseph brand marks are allowed to fall.
//
//  GENERATED by scripts/rank_rain_roster.py — edit that, not this.
//
//  The town-rain drop only ever shows a REAL local business logo, curated by the
//  offline `scripts/fetch_place_logos.py` pipeline into `places.logo_url` (see the
//  `20260723000000_places_logo.sql` migration for the nominative-use rationale — the
//  same marks already ride the map pins). There is nothing fabricated here.
//
//  WHY A FROZEN LIST, AND WHY 50: `places` carries no popularity signal — no rating,
//  no visit count — so "top" cannot be derived at runtime without inventing a metric,
//  which the house rule ("real data only, never seeded/inflated") forbids. Instead
//  these are the 50 strongest marks by PROVENANCE, ranked off the curation manifest
//  in the order the pipeline itself trusts:
//
//      1. apple-touch-icon (21) — own-site touch icon
//      2. agent-hunt       (16) — brand-mark hunt (strict)
//      3. agent-rescue     (10) — brand-mark hunt (rescue)
//      4. link-icon        ( 3) — own-site <link rel=icon>
//
//  ties broken by the source image's leading dimension, then name. The 27 approved
//  marks below the cut are weaker tiers (mostly round-2 "representative" ones, accurate
//  enough for a 26 pt pin but too loose for a 36 pt ball) — plus however many sit in the
//  SAME tier as the last one kept and simply lost the tie-break.
//
//  A missing id is harmless: the field falls back to whatever logo'd places the map
//  actually loaded, so a re-seeded `places` table degrades instead of breaking.
//

enum TownRainRoster {

    /// `places.id` of the 50 businesses whose marks may fall, best provenance first.
    static let placeIDs: [String] = [
        // Woodcrest of Country Manor  —  own-site touch icon, 500x500
        "1b601b20-6069-41bb-81dc-07ce8f3c65e1",
        // Sunny Mary Meadow  —  own-site touch icon, 300x300
        "448b008c-6c70-4591-b3e6-f094d6e41899",
        // Jupiter Moon Ice Cream - St. Joseph  —  own-site touch icon, 256x256
        "63fd93ff-7254-461c-9e64-b7c9169a56ae",
        // Two Bits Men's Grooming Salon  —  own-site touch icon, 256x256
        "bfcfe784-444a-44b5-835f-f3518032899c",
        // Thomsen's Garden Center  —  own-site touch icon, 200x200
        "f97e06d6-8cf9-4a75-9acd-b891ba516509",
        // Amy Hedtke - State Farm  —  own-site touch icon, 180x180
        "cf3c7388-f4ab-4522-ae1d-3d2a018c69a5",
        // Autobody 2000 Inc  —  own-site touch icon, 180x180
        "2f68442e-0399-4ac5-b60d-cc3237fa7746",
        // Brenny Transportation, Inc.  —  own-site touch icon, 180x180
        "2e89bbb6-8728-4ae6-8b8b-53c1629ba395",
        // Coborn's Grocery Store  —  own-site touch icon, 180x180
        "cbd3dec1-e1ed-4aa7-b32d-a02f7ae4ff8d",
        // Coborn's Pharmacy  —  own-site touch icon, 180x180
        "0ad2d330-9895-4735-9ff1-44c8b1d43b31",
        // Floor to Ceiling  —  own-site touch icon, 180x180
        "f974053c-c39a-4bb3-a6ef-bf163d232b7f",
        // Flour & Flower  —  own-site touch icon, 180x180
        "fed769b6-ec34-4cc6-bb05-8e7016e79aec",
        // Krewe Restaurant  —  own-site touch icon, 180x180
        "02280501-5d7d-4c2b-8a6b-2ec671ce9c7c",
        // Magnifi Financial  —  own-site touch icon, 180x180
        "805fce4e-79c4-428b-bbb2-ec2799fcaf82",
        // Minnesota Street Market, Food & Art Co-op  —  own-site touch icon, 180x180
        "7566738c-0349-4b9e-837b-f0c5ad5ed64e",
        // Neighbors Route 75  —  own-site touch icon, 180x180
        "3a51b1c2-eb45-4de4-8e38-5b48ca6ef44f",
        // Pierce Insurance Agency  —  own-site touch icon, 180x180
        "b4af59d7-0006-4fb7-8ff9-b79bb2e380c4",
        // Sal's Bar & Grill  —  own-site touch icon, 180x180
        "6b0f79a9-fff6-4e60-af98-a6a45ce51223",
        // The Wandering Cow Ice Cream  —  own-site touch icon, 180x180
        "01ed0060-197a-4ce3-bfb4-a15ba1777285",
        // WELL & Company St. Joseph  —  own-site touch icon, 180x180
        "16b7e598-78b2-4b10-a95b-e03958879fe0",
        // All Occasion Floral & Gifts  —  own-site touch icon, 120x120
        "ab44fdd8-302b-4523-abca-d087d89874f1",
        // White Peony Boutique  —  brand-mark hunt (strict), 4168x4167
        "606a751d-98e2-4f3a-8926-a1d3966592e0",
        // Blush Salon  —  brand-mark hunt (strict), 2875x2615
        "2b90146d-3652-4a02-b1a5-a5d132c62522",
        // Bo Diddley's Deli  —  brand-mark hunt (strict), 1500x914
        "dcc05e93-f05b-4143-b05c-d2a665bf72f2",
        // Golden Hour Tanning  —  brand-mark hunt (strict), 1500x1500
        "21e97746-5906-433f-8322-76fdb267b86a",
        // Little Saints Academy  —  brand-mark hunt (strict), 1242x755
        "d66e9cbf-d9d8-48e1-8fdf-412c8cf8202d",
        // W|R Home Co.  —  brand-mark hunt (strict), 1200x628
        "132e001b-e5b6-45fa-8db8-18ec28eb0c85",
        // United States Postal Service  —  brand-mark hunt (strict), 750x750
        "43d7228e-1fe5-487a-a30a-f53065818e22",
        // Hudson & Company  —  brand-mark hunt (strict), 599x600
        "339de4f9-8cdb-4e9c-8a4d-5a21ea96f86a",
        // St. Joseph Farmers' Market  —  brand-mark hunt (strict), 598x366
        "4a213aca-4735-40dd-9ac4-2b58696a0427",
        // Hansen & Company Woodworks  —  brand-mark hunt (strict), 500x500
        "5acceae4-ff09-40c7-9c46-e05d2857f018",
        // Milbert Johnson Family Dentistry  —  brand-mark hunt (strict), 500x500
        "1b35c7a9-713b-4da7-906e-4f74b0c2cb80",
        // Kay's Kitchen  —  brand-mark hunt (strict), 480x480
        "c109060a-ab8c-4197-bfc6-0d6cda06c964",
        // St Joseph Meat Market Inc  —  brand-mark hunt (strict), 402x426
        "8d32d5e6-2c7b-47d4-8b58-86afc63e6442",
        // Powerhouse Outdoor Equipment  —  brand-mark hunt (strict), 236x236
        "48258ad2-2c0c-4d87-ab65-950e7ab083e4",
        // Lee's Ace Hardware  —  brand-mark hunt (strict), 185x100
        "a5cd14e5-24b9-4d32-b57f-accb06cfdf1c",
        // Cedar Street Salon & Spa  —  brand-mark hunt (strict), 100x100
        "ffc8cb61-7783-4676-9e3d-ba8bc813b718",
        // Bruno Press  —  brand-mark hunt (rescue), 1500x2206
        "443332c9-0465-49f3-9afc-f5f103eb3bad",
        // Joetown Smashburger  —  brand-mark hunt (rescue), 1500x1502
        "d2737fe2-749c-4473-8346-35b2c5c774b0",
        // John Kuebelbeck American Legion Post 328  —  brand-mark hunt (rescue), 1280x1333
        "b8088f9f-a0b8-44ee-a63c-6242e10fe4d8",
        // Home Town Title  —  brand-mark hunt (rescue), 1024x1024
        "71571e13-d608-48c8-8755-f3e78bb391a8",
        // Solar Nails of St Joseph  —  brand-mark hunt (rescue), 631x315
        "2b59f99a-f6da-4c3a-86c3-a5b10b1ca8e3",
        // Bello Cucina | Italian  —  brand-mark hunt (rescue), 480x480
        "a36c5d37-f384-477b-b601-7f535b2ea7fd",
        // KPower Yoga  —  brand-mark hunt (rescue), 480x476
        "e70d7fad-c801-48f5-b874-2191defaf9b5",
        // The Perfect Fit, LLC  —  brand-mark hunt (rescue), 480x480
        "8cd01a3f-1441-4c1d-9aef-81419a6a75f0",
        // Trobec's Bus Service, Inc.  —  brand-mark hunt (rescue), 480x480
        "75afbf0c-cb83-462b-8d38-5890d9cd0f06",
        // Wildwood Ranch Maple Syrup  —  brand-mark hunt (rescue), 480x480
        "b367e8ab-b872-4142-b814-ecdd4e318d5d",
        // Bad Habit Brewing Company  —  own-site <link rel=icon>, 100x100
        "3f3c5259-67f9-491e-9af5-5c4b21a80b58",
        // Her Hair Studio  —  own-site <link rel=icon>, 100x119
        "4600a722-e962-4182-ad2a-035c04de3b74",
        // Milk & Honey Ciders  —  own-site <link rel=icon>, 100x100
        "796f4577-dd1a-49f6-aac5-49d3f8632ecb",
    ]

    /// The POIs eligible to fall, in roster order, from whatever the map has loaded.
    /// Falls back to every logo-bearing POI when the roster and the loaded rows do
    /// not overlap (a re-seed changes the uuids), so the drop is never empty on a
    /// map that plainly has logos.
    static func eligible(from pois: [POI]) -> [POI] {
        let withLogos = pois.filter { $0.logoURL != nil }
        let byID = Dictionary(withLogos.map { ($0.id, $0) }, uniquingKeysWith: { a, _ in a })
        let ranked = placeIDs.compactMap { byID[$0] }
        return ranked.isEmpty ? withLogos : ranked
    }
}
