#!/usr/bin/env python3
"""Compose this repo's AGENTS.md and CLAUDE.md from rules/ fragments.

The generated files must never be hand-edited. `bp_rules.py check` re-composes
them in memory and fails on any difference; that check runs in CI and in the
pre-commit hook, so a hand-edit cannot reach a branch.
"""
from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

BANNER = "<!-- generated by scripts/bp_rules.py — do not edit; edit rules/ instead -->\n"

ROUTER_MAX = 8 * 1024
SHIM_MAX = 2 * 1024
COMBINED_MAX = 9 * 1024

TARGETS: dict[str, list[str]] = {
    "AGENTS.md": ["rules/router"],
    "CLAUDE.md": ["rules/claude"],
}


def fragments(directory: Path) -> list[Path]:
    if not directory.is_dir():
        raise FileNotFoundError(
            f"no fragment directory: {directory} — this repo has not been "
            f"migrated to the rules/ layout yet"
        )
    return sorted(directory.glob("*.md"))


def compose(dirs: list[Path]) -> str:
    parts = [BANNER]
    for directory in dirs:
        for fragment in fragments(directory):
            parts.append(fragment.read_text(encoding="utf-8").rstrip() + "\n")
    return "\n".join(parts)


def generate(repo: Path) -> dict[str, str]:
    return {name: compose([repo / d for d in dirs]) for name, dirs in TARGETS.items()}


def cmd_build(repo: Path) -> int:
    for name, text in generate(repo).items():
        (repo / name).write_text(text, encoding="utf-8")
        print(f"wrote {name} ({len(text.encode('utf-8'))} B)")
    return 0


TRIGGER_ROW = re.compile(r"^\|[^|\n]+\|\s*`(docs/rules/[^`]+\.md)`\s*\|", re.M)


def check_sizes(repo: Path) -> int:
    failures = 0
    total = 0
    for name, limit in (("AGENTS.md", ROUTER_MAX), ("CLAUDE.md", SHIM_MAX)):
        path = repo / name
        size = len(path.read_bytes()) if path.exists() else 0
        total += size
        if size > limit:
            failures += 1
            print(
                f"::error::{name} is {size} B, over its {limit} B cap. "
                f"Move a section into docs/rules/ and add a trigger-table row for it."
            )
    if total > COMBINED_MAX:
        failures += 1
        print(f"::error::router + shim is {total} B, over the {COMBINED_MAX} B always-on cap.")
    return failures


def check_triggers(repo: Path) -> int:
    agents = repo / "AGENTS.md"
    if not agents.exists():
        print("::error::AGENTS.md is missing — run: python3 scripts/bp_rules.py build")
        return 1
    referenced = set(TRIGGER_ROW.findall(agents.read_text(encoding="utf-8")))
    leaf_dir = repo / "docs" / "rules"
    leaves = {
        str(p.relative_to(repo)).replace("\\", "/")
        for p in leaf_dir.glob("*.md")
        if p.name != "HARVEST-LEDGER.md"
    }
    failures = 0
    for missing in sorted(referenced - leaves):
        failures += 1
        print(f"::error::the trigger table points at {missing}, which does not exist")
    for orphan in sorted(leaves - referenced):
        failures += 1
        print(
            f"::error::{orphan} is not reachable from the trigger table — "
            f"no agent will ever be told to read it"
        )
    return failures


def cmd_check(repo: Path) -> int:
    failures = 0
    for name, want in generate(repo).items():
        path = repo / name
        have = path.read_text(encoding="utf-8") if path.exists() else ""
        if have != want:
            failures += 1
            print(
                f"::error::{name} is out of sync with rules/. "
                f"Regenerate with: python3 scripts/bp_rules.py build"
            )
            sys.stdout.writelines(
                difflib.unified_diff(
                    have.splitlines(True),
                    want.splitlines(True),
                    fromfile=f"{name} (on disk)",
                    tofile=f"{name} (composed from rules/)",
                )
            )
    failures += check_sizes(repo)
    failures += check_triggers(repo)
    return 1 if failures else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate or verify this repo's agent instruction files.")
    parser.add_argument("command", choices=["build", "check"])
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parent.parent)
    args = parser.parse_args(argv)
    try:
        return cmd_build(args.repo) if args.command == "build" else cmd_check(args.repo)
    except FileNotFoundError as exc:
        print(f"::error::{exc}")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
