#!/usr/bin/env python3
"""Rank the curated place logos and emit BlockParty/Features/Map/TownRain/TownRainRoster.swift.

`places` carries no popularity signal — no rating, no visit count — so "the top 50
businesses" cannot be derived at runtime without inventing a metric, which the house rule
("real data only, never seeded/inflated") forbids. So rank by PROVENANCE instead, using the
curation manifest the logo pipeline already writes, in the order that pipeline trusts:

    apple-touch-icon  the business's own site's own touch icon
    agent-hunt        round-1 strict brand-mark hunt
    agent-rescue      round-1 rescue pass
    link-icon         the site's declared <link rel=icon>
    agent-round2      round-2 relaxed "representative" marks (parent-institution logos etc.)
    google-favicon    last resort

ties broken by source resolution, then name. Round-2 marks are accurate enough for a 26 pt
pin but too loose for a 36 pt ball, so the default cut of 50 lands just above them.

    python3 scripts/rank_rain_roster.py [path/to/place-logos-manifest.json] [--count 50]

The manifest lives with the logo pipeline (docs/place-logos-manifest.json). Re-run after any
logo re-curation and commit the regenerated Swift file.
"""

import argparse
import json
import pathlib
import sys

TIERS = [
    ("apple-touch-icon", "own-site touch icon"),
    ("agent-hunt", "brand-mark hunt (strict)"),
    ("agent-rescue", "brand-mark hunt (rescue)"),
    ("link-icon", "own-site <link rel=icon>"),
    ("agent-round2", "representative mark (round 2)"),
    ("google-favicon", "google favicon service"),
]
TIER_RANK = {name: i for i, (name, _) in enumerate(TIERS)}
TIER_LABEL = dict(TIERS)

# Marks that are curated and accurate but must NOT fall: the drop is meant to be the
# town's OWN businesses, and a national franchise's logo bouncing past reads as an ad.
# Keyed by the manifest's `name`, with the reason, because a future re-curation will
# re-introduce them and the next person needs to know why they were cut.
#
# Two grounds only. Anything not listed here falls.
EXCLUDED = {
    # --- chain / franchise / multi-site operator / government / institution ---
    "Coborn's Grocery Store": "regional grocery chain (MN/ND/SD)",
    "Coborn's Pharmacy": "regional grocery chain (MN/ND/SD)",
    "Amy Hedtke - State Farm": "national insurance franchise",
    "Floor to Ceiling": "national franchise / buying group",
    "Lee's Ace Hardware": "Ace Hardware national brand",
    "Bo Diddley's Deli": "Minnesota chain",
    "Magnifi Financial": "regional credit union, many branches",
    "Kensington Bank": "regional bank, many branches",
    "Sentry Bank": "regional bank, many branches",
    "TireMaxx Service Centers": "multi-location service chain",
    "CentraCare - St. Joseph Clinic": "regional health system",
    "Woodcrest of Country Manor": "regional senior-care operator",
    "United States Postal Service": "federal agency, not a local business",
    "CSB Benedicta Arts Center Galleries (Gorecki Gallery)":
        "college facility, not a business",

    # --- local, but back-office: no storefront the public would recognise ---
    "Brenny Transportation, Inc.": "B2B freight",
    "AMS Tax & Accounting Solutions, PA": "professional services, by appointment",
    "Home Town Title": "title and closing services",
    "Bruno Press": "commercial printing",
    "Hansen & Company Woodworks": "custom fabrication, not a storefront",
    "Groundsman LLC": "landscaping contractor",
    "The Perfect Fit, LLC": "unidentifiable to the public from the name or mark",
}

HEADER = '''//
//  TownRainRoster.swift
//  Block Party — which real St. Joseph brand marks are allowed to fall.
//
//  GENERATED by scripts/rank_rain_roster.py — edit that, not this.
//
//  The town-rain drop only ever shows a REAL local business logo, curated by the
//  offline `scripts/fetch_place_logos.py` pipeline into `places.logo_url` (see the
//  `20260723000000_places_logo.sql` migration for the nominative-use rationale — the
//  same marks already ride the map pins). There is nothing fabricated here.
//
//  LOCAL ONLY. Chains, franchises, multi-branch banks, regional health and senior-care
//  operators, and government/college facilities are cut — a national brand's logo
//  bouncing across the town map reads as an ad, not as the town. So are locally-owned
//  but back-office businesses (freight, title, printing) with no storefront the public
//  would recognise. The exclusion list, with a reason for every entry, lives in
//  scripts/rank_rain_roster.py — that is the file to edit, not this one.
//
//  ORDERED BY PROVENANCE: `places` carries no popularity signal — no rating, no visit
//  count — so "best known" cannot be derived at runtime without inventing a metric,
//  which the house rule ("real data only, never seeded/inflated") forbids. These are
//  the {count} eligible marks ranked by how the curation pipeline sourced each one:
//
{tier_lines}
//
//  ties broken by the source image's leading dimension, then name.
//
//  A missing id is harmless: the field falls back to whatever logo'd places the map
//  actually loaded, so a re-seeded `places` table degrades instead of breaking.
//

enum TownRainRoster {{

    /// `places.id` of the {count} local businesses whose marks may fall, best
    /// provenance first.
    static let placeIDs: [String] = [
'''

FOOTER = '''    ]

    /// The POIs eligible to fall, in roster order, from whatever the map has loaded.
    /// Falls back to every logo-bearing POI when the roster and the loaded rows do
    /// not overlap (a re-seed changes the uuids), so the drop is never empty on a
    /// map that plainly has logos.
    static func eligible(from pois: [POI]) -> [POI] {
        let withLogos = pois.filter { $0.logoURL != nil }
        let byID = Dictionary(withLogos.map { ($0.id, $0) }, uniquingKeysWith: { a, _ in a })
        let ranked = placeIDs.compactMap { byID[$0] }
        return ranked.isEmpty ? withLogos : ranked
    }
}
'''

DEFAULT_MANIFEST = pathlib.Path(
    "~/Documents/block-party-poi-logos/docs/place-logos-manifest.json"
).expanduser()


def width(entry):
    """Leading dimension of `source_px` ("500x500" -> 500); 0 when absent or malformed."""
    try:
        return int(str(entry.get("source_px", "0x0")).split("x")[0])
    except (ValueError, AttributeError):
        return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest", nargs="?", default=str(DEFAULT_MANIFEST))
    ap.add_argument("--count", type=int, default=0,
                    help="cap the roster; 0 (default) keeps every eligible local mark")
    ap.add_argument(
        "--out",
        default="BlockParty/Features/Map/TownRain/TownRainRoster.swift",
        help="written relative to the repo root",
    )
    args = ap.parse_args()

    path = pathlib.Path(args.manifest).expanduser()
    if not path.exists():
        sys.exit(f"manifest not found: {path}")

    manifest = json.loads(path.read_text())
    approved = [e for e in manifest["entries"] if e.get("status") == "approved"]

    cut = [e for e in approved if e["name"] in EXCLUDED]
    approved = [e for e in approved if e["name"] not in EXCLUDED]
    unknown = set(EXCLUDED) - {e["name"] for e in cut}
    if unknown:
        print("WARNING — excluded names not present in the manifest (renamed?):")
        for n in sorted(unknown):
            print(f"    {n}")
    if args.count and len(approved) < args.count:
        sys.exit(
            f"only {len(approved)} eligible local marks — cannot fill a roster of "
            f"{args.count}. Re-run the logo pipeline or lower --count."
        )

    approved.sort(key=lambda e: (TIER_RANK.get(e.get("candidate"), len(TIERS)), -width(e), e["name"]))
    top = approved[: args.count] if args.count else approved

    counts = {}
    for e in top:
        counts[e.get("candidate")] = counts.get(e.get("candidate"), 0) + 1
    tier_lines = "\n".join(
        f"//      {i + 1}. {name:<16} ({counts[name]:>2}) — {TIER_LABEL[name]}"
        for i, (name, _) in enumerate(TIERS)
        if counts.get(name)
    )

    body = "\n".join(
        f'        // {e["name"]}  —  {TIER_LABEL.get(e.get("candidate"), e.get("candidate"))}, {e.get("source_px")}\n'
        f'        "{e["id"]}",'
        for e in top
    )

    out = pathlib.Path(args.out)
    out.write_text(
        HEADER.format(count=args.count, tier_lines=tier_lines, rest=len(approved) - args.count)
        + body
        + "\n"
        + FOOTER
    )
    print(f"wrote {out} — {len(top)} local marks "
          f"({len(cut)} chains / back-office cut from {len(top) + len(cut)} approved)")
    for name, _ in TIERS:
        if counts.get(name):
            print(f"  {name:<18} {counts[name]}")
    print("\ncut:")
    for e in sorted(cut, key=lambda e: e["name"]):
        print(f"  {e['name']:<52} {EXCLUDED[e['name']]}")


if __name__ == "__main__":
    main()
