-- places seed — the curated St. Joseph POI set the map renders (39 venues:
-- 20 food, 19 business), as of 2026-07-15. Reproducible + diffable record of what
-- PlaceSeeder swept from Google Nearby Search, after the on-brand curation pass:
--   • dropped a campus athletic facility (Claire Lynch Hall) and heavy-industrial
--     fringe 1.5–2 km out (towing, materials/parts distributors) — not neighborly POIs;
--   • added Bad Habit Brewing (its primaryType `brewery` was outside PlaceSeeder's
--     discovery groups, now added there so a re-sweep finds it).
-- Marquee downtown venues use hand-curated KnownVenues coordinates; the rest keep
-- Google's. Photos are never seeded — re-fetched live via place_id at display time.
--
-- Idempotent: `on conflict (place_id) do nothing` so re-applying (or a live PlaceSeeder
-- run) never clobbers curated rows. Depends on 20260715000000_places.sql (the table).

insert into public.places (place_id, name, lat, lon, family, primary_type, types, address, source) values
  ('ChIJETP5ry5ZtFIR-go-9evnRwc', 'Blush Salon', 45.565682, -94.3219915, 'business', 'beauty_salon', '{beauty_salon,service,point_of_interest,establishment}'::text[], '106 2nd Ave NW, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJK3yn58VZtFIRib7XSlplMK4', 'CMS Autobody', 45.5680163, -94.3166779, 'business', 'car_repair', '{car_repair,service,point_of_interest,establishment}'::text[], '109 Cedar St E, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJ-bSQp6VZtFIRadBh8Mlrxws', 'Coborn''s Grocery Store', 45.5680828, -94.2972268, 'business', 'grocery_store', '{grocery_store,food_store,store,point_of_interest,food,establishment}'::text[], '1500 Elm St E, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJ-bSQp6VZtFIRsrFXg1RYwFs', 'Coborn''s Pharmacy', 45.567911, -94.297185, 'business', 'pharmacy', '{pharmacy,drugstore,store,health,point_of_interest,establishment}'::text[], '1500 Elm St E, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJya0xj_FZtFIR9HcG5x8Qn3A', 'Dollar General', 45.5685365, -94.3087547, 'business', 'discount_store', '{gift_shop,drugstore,convenience_store,discount_store,grocery_store,toy_store,food_store,store,health,point_of_interest,food,establishment}'::text[], '604 Elm St E, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJD2riN8VZtFIRehXwgKUkA8c', 'Holiday Stationstores', 45.5680373, -94.3182154, 'business', 'convenience_store', '{convenience_store,sandwich_shop,breakfast_restaurant,coffee_shop,cafe,food_store,store,restaurant,food,point_of_interest,establishment}'::text[], '304 College Ave N, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJKaje0DFZtFIR3zQYUG406MU', 'KPower Yoga', 45.5656596, -94.3211459, 'business', 'yoga_studio', '{yoga_studio,fitness_center,sports_complex,gym,sports_school,sports_activity_location,health,point_of_interest,establishment}'::text[], '109 W Ash St, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJzeuDh9pZtFIRvj4UdbHclJE', 'Kwik Trip', 45.567036, -94.3218671, 'business', 'gas_station', '{gas_station,atm,convenience_store,car_wash,liquor_store,finance,food_store,store,service,point_of_interest,food,establishment}'::text[], '200 2nd Ave NW, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJQ08RPqlZtFIRz9DQ5PHSyYk', 'Kwik Trip #575', 45.5640837, -94.2918398, 'business', 'gas_station', '{gas_station,atm,convenience_store,car_wash,liquor_store,finance,food_store,store,service,point_of_interest,food,establishment}'::text[], '15 20th Ave SE, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJPZImC8ZZtFIR9_fV1pe_1B8', 'Lee''s Ace Hardware', 45.5680919, -94.3144188, 'business', 'hardware_store', '{hardware_store,home_improvement_store,home_goods_store,building_materials_store,store,point_of_interest,establishment}'::text[], '213 Cedar St E #785, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJ-bSQp6VZtFIReXOuDq-PFwQ', 'Magnifi Financial', 45.5686964, -94.3001312, 'business', 'finance', '{atm,consultant,finance,service,association_or_organization,point_of_interest,establishment}'::text[], '1300 Elm St E, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJh8mk0M9ZtFIR9Y58T0xGDdw', 'Minnesota Street Market, Food & Art Co-op', 45.5646135, -94.3190773, 'business', 'health_food_store', '{health_food_store,convenience_store,art_gallery,grocery_store,food_store,store,health,point_of_interest,food,establishment}'::text[], '27 W Minnesota St, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJQ_UrhrlZtFIRuBFsbDvOtck', 'O''Reilly Auto Parts', 45.5688869, -94.3010209, 'business', 'auto_parts_store', '{auto_parts_store,truck_dealer,electronics_store,car_repair,store,service,point_of_interest,establishment}'::text[], '1160 Elm St E, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJZ_M1dcZZtFIRj1WUp5Owhks', 'Powerhouse Outdoor Equipment', 45.5681037, -94.3147811, 'business', 'store', '{store,service,point_of_interest,establishment}'::text[], '207 Cedar St E, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJn0f45cZZtFIReWj8etT4Z5w', 'Sentry Bank', 45.5667271, -94.3091539, 'business', 'bank', '{bank,atm,finance,point_of_interest,establishment}'::text[], '400 4th Ave NE, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJCZ-6KbpZtFIRT_g9iebWlWM', 'Snap Fitness St. Joseph', 45.5682929, -94.3068619, 'business', 'gym', '{gym,sports_activity_location,health,point_of_interest,establishment}'::text[], '708 Elm St E, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJtSr6H7hZtFIRwLvX5L__hOI', 'Solar Nails of St Joseph', 45.5668281, -94.3076473, 'business', 'nail_salon', '{nail_salon,beauty_salon,service,point_of_interest,establishment}'::text[], '710 Co Rd 75 #107, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJoSTgPNBZtFIR8Uaf5spTM9U', 'St Joseph Meat Market Inc', 45.5651773, -94.3198923, 'business', 'butcher_shop', '{butcher_shop,food_store,manufacturer,store,service,point_of_interest,food,establishment}'::text[], '26 1st Ave NW, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJvceKY9BZtFIRrc2jwo27hGA', 'United States Postal Service', 45.5656114, -94.3215148, 'business', 'post_office', '{post_office,local_government_office,government_office,finance,service,association_or_organization,point_of_interest,establishment}'::text[], '117 W Ash St, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJIQh2uc9ZtFIRmCpM-CN5dTw', 'Bad Habit Brewing Company', 45.56557, -94.31863, 'food', 'brewery', '{brewery,food,manufacturer,service,point_of_interest,establishment}'::text[], '25 College Ave N, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJX5Keuc9ZtFIRwF6PHvJmcdk', 'Bello Cucina | Italian', 45.5649451, -94.3176044, 'food', 'italian_restaurant', '{italian_restaurant,restaurant,food,point_of_interest,establishment}'::text[], '15 E Minnesota St, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJxSjlws9ZtFIR91vPZw-Cw2s', 'Bo Diddley''s Deli', 45.5652164, -94.3183144, 'food', 'sandwich_shop', '{sandwich_shop,deli,fast_food_restaurant,food_store,store,restaurant,food,point_of_interest,establishment}'::text[], '19 College Ave N, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJv9tI5l9ZtFIRYzLLIRe5zr8', 'Caribou Coffee', 45.568063, -94.297141, 'food', 'coffee_shop', '{coffee_shop,breakfast_restaurant,cafe,food_store,store,restaurant,food,point_of_interest,establishment}'::text[], '1500 Elm St E, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJhWzY0rlZtFIRrMjMCssCjy0', 'China One', 45.566948, -94.3074158, 'food', 'chinese_restaurant', '{chinese_restaurant,restaurant,food,point_of_interest,establishment}'::text[], '710 Co Rd 75 #108, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJO6rMKx5ZtFIRdVZTpacbThY', 'Flour & Flower', 45.5655485, -94.3176634, 'food', 'bakery', '{bakery,coffee_shop,cafe,meal_takeaway,market,food_store,store,restaurant,food,point_of_interest,establishment}'::text[], '26 College Ave N Ste 104, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJfSYLxM9ZtFIRnStgMgXkQqs', 'Gary''s Pizza', 45.5650174, -94.3183061, 'food', 'pizza_restaurant', '{pizza_restaurant,italian_restaurant,meal_delivery,food_delivery,restaurant,food,point_of_interest,establishment}'::text[], '17 College Ave N, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJ8-AGArJZtFIRPdapnHeQWpc', 'Jupiter Moon Ice Cream - St. Joseph', 45.5649999, -94.3167926, 'food', 'ice_cream_shop', '{ice_cream_shop,dessert_shop,confectionery,food_store,store,food,point_of_interest,establishment}'::text[], '15 E Minnesota St Ste 108, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJs3OYN8VZtFIRD_rcmlDNcGo', 'Kay''s Kitchen', 45.567907, -94.319214, 'food', 'restaurant', '{restaurant,buffet_restaurant,bakery,food_store,store,food,point_of_interest,establishment}'::text[], '303 College Ave N, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJVUdOHB1ZtFIRMciOBnBKbRI', 'Krewe Restaurant', 45.56559, -94.31797, 'food', 'cajun_restaurant', '{cajun_restaurant,catering_service,american_restaurant,food_delivery,event_venue,restaurant,food,point_of_interest,service,establishment}'::text[], '24 College Ave N Ste 104, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJzdcewc9ZtFIR7BrOxmjRYLw', 'La Playette Bar', 45.5652181, -94.3179549, 'food', 'bar', '{bar,point_of_interest,establishment}'::text[], '16 College Ave N, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJ67OQp6VZtFIRfxt_gnI6w-g', 'McDonald''s', 45.568044, -94.3011532, 'food', 'fast_food_restaurant', '{fast_food_restaurant,sandwich_shop,breakfast_restaurant,coffee_shop,hamburger_restaurant,cafe,american_restaurant,food_store,store,restaurant,food,point_of_interest,establishment}'::text[], '1180 Elm St E, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJz-W_cL1ZtFIRnuug5NtJwqA', 'Neighbors Route 75', 45.5638797, -94.2899203, 'food', 'restaurant', '{restaurant,american_restaurant,food,point_of_interest,establishment}'::text[], '2010 Co Rd 75, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJsUeENdBZtFIRk-BROmx3-Fs', 'Sal''s Bar & Grill', 45.5644264, -94.320549, 'food', 'bar_and_grill', '{bar_and_grill,bar,restaurant,food,point_of_interest,establishment}'::text[], '109 W Minnesota St, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJ1YBBDWFXtFIRpN_AoK_WPi8', 'Subway', 45.5681118, -94.3204911, 'food', 'sandwich_shop', '{sandwich_shop,fast_food_restaurant,catering_service,meal_takeaway,food_delivery,restaurant,food,point_of_interest,service,establishment}'::text[], '217 Co Rd 75, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJ48M5DWFXtFIRhX2uzqCRgPo', 'Taco John''s', 45.5681086, -94.3200383, 'food', 'fast_food_restaurant', '{fast_food_restaurant,taco_restaurant,breakfast_restaurant,burrito_restaurant,meal_takeaway,mexican_restaurant,restaurant,food,point_of_interest,establishment}'::text[], '211 Co Rd 75, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJy9h63EtZtFIRYVJtkqYK2zQ', 'The House Food and Tap', 45.5641341, -94.3219243, 'food', 'restaurant', '{restaurant,food,point_of_interest,establishment}'::text[], '13 2nd Ave NW, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJmTKJ0M9ZtFIRm7FAmBzwApc', 'The Local Blend', 45.56483, -94.31841, 'food', 'coffee_shop', '{coffee_shop,cafe,food_store,store,restaurant,food,point_of_interest,establishment}'::text[], '19 W Minnesota St, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJC3QB0c9ZtFIR-wlf_YramxY', 'The Middy', 45.5647076, -94.3187021, 'food', 'bar', '{bar,point_of_interest,establishment}'::text[], '21 W Minnesota St, St Joseph, MN 56374, USA', 'google_nearby'),
  ('ChIJFfdMxRVZtFIR77H-NqLzUTc', 'The Wandering Cow Ice Cream', 45.565066, -94.3178751, 'food', 'ice_cream_shop', '{ice_cream_shop,dessert_shop,confectionery,food_store,store,food,point_of_interest,establishment}'::text[], '14 College Ave N Ste b, St Joseph, MN 56374, USA', 'google_nearby')
on conflict (place_id) do nothing;
